export default {
  port: 'PORT',
  nodeEnv: 'NODE_ENV',
  setupStatus: 'SETUP_STATUS',
  organization: 'ORGANIZATION',
  postgresConfig: {
    host: 'POSTGRES_HOST',
    port: 'POSTGRES_PORT',
    username: 'POSTGRES_USER',
    password: 'POSTGRES_PASSWORD',
    database: 'POSTGRES_DB',
  },
  accessTokenPrivateKey: 'ACCESS_PRIVATE_KEY',
  accessTokenPublicKey: 'ACCESS_PUBLIC_KEY',
  refreshTokenPrivateKey: 'REFRESH_PRIVATE_KEY',
  refreshTokenPublicKey: 'REFRESH_PUBLIC_KEY',
  awsAccessKeyID: 'AWS_ACCESS_KEY_ID',
  awsSecretAccessKey: 'AWS_SECRET_ACCESS_KEY',
  bucketName: 'BUCKET_NAME',
};
