import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1688598441605 implements MigrationInterface {
    name = 'Migrations1688598441605'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "questionResponse" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "response" character varying NOT NULL, "questionnaireResponseId" integer, CONSTRAINT "PK_c594b6302170e8c1f74acb0e7a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."questions_responsetype_enum" AS ENUM('scale', 'number', 'boolean', 'text')`);
        await queryRunner.query(`CREATE TABLE "questions" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "question" character varying NOT NULL, "responseType" "public"."questions_responsetype_enum" NOT NULL DEFAULT 'scale', "questionnaireId" integer, "questionResponsesId" integer, CONSTRAINT "PK_08a6d4b0f49ff300bf3a0ca60ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "questionnaires" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "dateToShow" character varying NOT NULL, "title" character varying NOT NULL, CONSTRAINT "PK_a01d7cdea895ed9796b29233610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "questionnaireResponses" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "dateResponded" character varying NOT NULL, "userId" integer, "questionnaireId" integer, CONSTRAINT "PK_a7b36cdc1bc806435fe616a3a19" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."completedExercises_type_enum" AS ENUM('throw', 'timed', 'weighted', 'bodyweight', 'command')`);
        await queryRunner.query(`CREATE TABLE "completedExercises" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "exerciseId" integer NOT NULL, "title" character varying NOT NULL, "date" character varying, "type" "public"."completedExercises_type_enum" NOT NULL DEFAULT 'bodyweight', "sets" integer NOT NULL, "reps" integer NOT NULL, "prescribedWeight" integer NOT NULL, "recordedValue" integer NOT NULL, "athleteId" integer, "completedWorkoutId" integer, CONSTRAINT "PK_c4207dfe5cd5f122132d1f801af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pitches_type_enum" AS ENUM('fastball', 'changeup', 'curveball', 'slider', 'twoseam', 'cutter', 'sinker', 'slurve')`);
        await queryRunner.query(`CREATE TYPE "public"."pitches_throwtype_enum" AS ENUM('longtoss', 'drill', 'mound', 'pulldown', 'flatground', 'plyo')`);
        await queryRunner.query(`CREATE TABLE "pitches" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "date" character varying NOT NULL, "type" "public"."pitches_type_enum" NOT NULL DEFAULT 'fastball', "throwType" "public"."pitches_throwtype_enum" NOT NULL DEFAULT 'drill', "velocity" integer NOT NULL, "distance" integer NOT NULL, "xCoordinate" integer, "yCoordinate" integer, "athleteId" integer, "completedWorkoutId" integer, CONSTRAINT "PK_c0ab1fa10a5750d17b935c60854" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."completedWorkouts_type_enum" AS ENUM('none', 'lift', 'command', 'throw', 'mobility')`);
        await queryRunner.query(`CREATE TABLE "completedWorkouts" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "title" character varying NOT NULL, "type" "public"."completedWorkouts_type_enum" NOT NULL DEFAULT 'lift', "athleteId" integer, CONSTRAINT "PK_ac38bbf69323a3391c96496179e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "files" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "dateUploaded" character varying NOT NULL, "type" character varying, "name" character varying, "src" character varying NOT NULL, "description" character varying, "completedWorkoutId" integer, "ownerId" integer, CONSTRAINT "PK_6c16b9093a142e0e7613b04a3d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chats" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0117647b3c4a4e5ff198aeb6206" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "body" character varying NOT NULL, "chatId" integer, "senderId" integer, "recipientId" integer, CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('user', 'athlete', 'coach', 'admin')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('approved', 'locked')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'user', "status" "public"."users_status_enum" NOT NULL DEFAULT 'approved', "verified" boolean NOT NULL DEFAULT false, "verificationCode" text, "passwordResetCode" text, "profilePictureId" integer, "athleteId" integer, "coachId" integer, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "REL_f127c2c8d3618ee635c96c68c4" UNIQUE ("profilePictureId"), CONSTRAINT "REL_2739419b1868e73398b68253f0" UNIQUE ("athleteId"), CONSTRAINT "REL_0b00d632e056e05b96b7c2594b" UNIQUE ("coachId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "email_index" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "coaches" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "organization" character varying NOT NULL, "userId" integer, CONSTRAINT "REL_aff053106aac14fb7a780800bc" UNIQUE ("userId"), CONSTRAINT "PK_eddaece1a1f1b197fa39e6864a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "athleteSchedule" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "workouts" character varying, "userId" integer, CONSTRAINT "REL_dabf8cf192c6ba7583edacd3cd" UNIQUE ("userId"), CONSTRAINT "PK_710caa88cbf7cb41ce9c3c254f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."athletes_handed_enum" AS ENUM('left', 'right')`);
        await queryRunner.query(`CREATE TYPE "public"."athletes_level_enum" AS ENUM('highschool', 'college', 'professional')`);
        await queryRunner.query(`CREATE TABLE "athletes" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "height" character varying NOT NULL, "weight" integer NOT NULL, "age" integer, "organization" character varying NOT NULL, "handed" "public"."athletes_handed_enum" NOT NULL DEFAULT 'right', "level" "public"."athletes_level_enum" NOT NULL DEFAULT 'college', "userId" integer, "coachId" integer, "athleteScheduleId" integer, CONSTRAINT "REL_fede6c4b866bf0a869cfba5e0a" UNIQUE ("userId"), CONSTRAINT "REL_0fda0671cfa1c3156b6557a5ad" UNIQUE ("athleteScheduleId"), CONSTRAINT "PK_3b92d2bd187b2b2d27d4c47f1c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "assessmentResponses" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "dateResponded" character varying NOT NULL, "athleteId" integer, "assessmentId" integer, CONSTRAINT "PK_e1f7b3f9533a5b44785476b000c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "assessmentItemResponse" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "response" character varying NOT NULL, "assessmentItemId" integer, "assessmentResponseId" integer, CONSTRAINT "PK_61deb111a5fe1e6c2a83231f3d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "assessmentItems" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "title" character varying, "type" character varying, "link" character varying, "notes" character varying, "assessmentId" integer, "assessmentItemResponsesId" integer, CONSTRAINT "PK_753c79c0d1c8f3969a0deccff30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "assessments" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "title" character varying NOT NULL, "type" character varying NOT NULL, CONSTRAINT "PK_a3442bd80a00e9111cefca57f6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "workouts" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "title" character varying NOT NULL, "type" character varying, "description" character varying, "notes" character varying, CONSTRAINT "PK_5b2319bf64a674d40237dbb1697" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "settings" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "warmUpColor" character varying, "mobilityColor" character varying, "liftColor" character varying, "throwColor" character varying, "controlColor" character varying, CONSTRAINT "PK_0669fe20e252eb692bf4d344975" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."exercises_type_enum" AS ENUM('throw', 'timed', 'weighted', 'bodyweight', 'command')`);
        await queryRunner.query(`CREATE TABLE "exercises" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "title" character varying, "type" "public"."exercises_type_enum" NOT NULL DEFAULT 'bodyweight', "description" character varying, "link" character varying, "notes" character varying, "sets" integer DEFAULT '0', "reps" integer DEFAULT '0', "time" integer DEFAULT '0', "onDashboardId" integer, "onLeaderboardId" integer, CONSTRAINT "PK_c4c46f5fa89a58ba7c2d894e3c3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "valid" boolean NOT NULL DEFAULT true, "userId" integer, CONSTRAINT "REL_57de40bc620f456c7311aa3a1e" UNIQUE ("userId"), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tickets" ("id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "subject" character varying NOT NULL, "sender" integer NOT NULL, "recipient" integer NOT NULL, "body" character varying NOT NULL, CONSTRAINT "PK_343bc942ae261cf7a1377f48fd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users_chats_chats" ("usersId" integer NOT NULL, "chatsId" integer NOT NULL, CONSTRAINT "PK_f91b45c81a0fabab4035694d651" PRIMARY KEY ("usersId", "chatsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_017810da2080af92ae589a06db" ON "users_chats_chats" ("usersId") `);
        await queryRunner.query(`CREATE INDEX "IDX_6628b681b44362637c96ad2fab" ON "users_chats_chats" ("chatsId") `);
        await queryRunner.query(`CREATE TABLE "workouts_exercises_exercises" ("workoutsId" integer NOT NULL, "exercisesId" integer NOT NULL, CONSTRAINT "PK_d57f63eed393481ff1200d4c150" PRIMARY KEY ("workoutsId", "exercisesId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bfc966116a382a6f6b845ac15d" ON "workouts_exercises_exercises" ("workoutsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_13937e69e8ba290d5faafcec75" ON "workouts_exercises_exercises" ("exercisesId") `);
        await queryRunner.query(`ALTER TABLE "questionResponse" ADD CONSTRAINT "FK_d4fe15ca6022f0f92008b6e203f" FOREIGN KEY ("questionnaireResponseId") REFERENCES "questionnaireResponses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_a25e444b4f0c7e666a72b702880" FOREIGN KEY ("questionnaireId") REFERENCES "questionnaires"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questions" ADD CONSTRAINT "FK_6f580671b044b44f55871b62330" FOREIGN KEY ("questionResponsesId") REFERENCES "questionResponse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questionnaireResponses" ADD CONSTRAINT "FK_d5a8869edfbeb74a0d8d1f28a9e" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "questionnaireResponses" ADD CONSTRAINT "FK_9fff1a9413dfe068414944d779d" FOREIGN KEY ("questionnaireId") REFERENCES "questionnaires"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "completedExercises" ADD CONSTRAINT "FK_d787040da51c16f05ca5aef40af" FOREIGN KEY ("athleteId") REFERENCES "athletes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "completedExercises" ADD CONSTRAINT "FK_47eadb019d4da349af42995da72" FOREIGN KEY ("completedWorkoutId") REFERENCES "completedWorkouts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pitches" ADD CONSTRAINT "FK_bbcb61278db2649bb7bbe392d74" FOREIGN KEY ("athleteId") REFERENCES "athletes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pitches" ADD CONSTRAINT "FK_6f8fe7f1b32aca0b9dba1a9b4a4" FOREIGN KEY ("completedWorkoutId") REFERENCES "completedWorkouts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "completedWorkouts" ADD CONSTRAINT "FK_a53f1794038304c744bacaa71fc" FOREIGN KEY ("athleteId") REFERENCES "athletes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_9415c86c94e166b3a99bd3986a4" FOREIGN KEY ("completedWorkoutId") REFERENCES "completedWorkouts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "files" ADD CONSTRAINT "FK_a23484d1055e34d75b25f616792" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_36bc604c820bb9adc4c75cd4115" FOREIGN KEY ("chatId") REFERENCES "chats"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_f548818d46a1315d4e1d5e62da5" FOREIGN KEY ("recipientId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_f127c2c8d3618ee635c96c68c4b" FOREIGN KEY ("profilePictureId") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_2739419b1868e73398b68253f08" FOREIGN KEY ("athleteId") REFERENCES "athletes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_0b00d632e056e05b96b7c2594bc" FOREIGN KEY ("coachId") REFERENCES "coaches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coaches" ADD CONSTRAINT "FK_aff053106aac14fb7a780800bce" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "athleteSchedule" ADD CONSTRAINT "FK_dabf8cf192c6ba7583edacd3cd3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "athletes" ADD CONSTRAINT "FK_fede6c4b866bf0a869cfba5e0ab" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "athletes" ADD CONSTRAINT "FK_6318488ea7158c8ab65882419d4" FOREIGN KEY ("coachId") REFERENCES "coaches"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "athletes" ADD CONSTRAINT "FK_0fda0671cfa1c3156b6557a5add" FOREIGN KEY ("athleteScheduleId") REFERENCES "athleteSchedule"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessmentResponses" ADD CONSTRAINT "FK_b14ffe8cedb517032ecc08d20a0" FOREIGN KEY ("athleteId") REFERENCES "athletes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessmentResponses" ADD CONSTRAINT "FK_78458898b3993eb848a6782c071" FOREIGN KEY ("assessmentId") REFERENCES "assessments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessmentItemResponse" ADD CONSTRAINT "FK_085b962c57b4c4f501207a3350f" FOREIGN KEY ("assessmentItemId") REFERENCES "assessmentItems"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessmentItemResponse" ADD CONSTRAINT "FK_de0a3daae28e766c7b11e89f9e8" FOREIGN KEY ("assessmentResponseId") REFERENCES "assessmentResponses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessmentItems" ADD CONSTRAINT "FK_1fe04f9a82d0a5e58b9c3da8d0c" FOREIGN KEY ("assessmentId") REFERENCES "assessments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "assessmentItems" ADD CONSTRAINT "FK_4f5214bc85f5fda317f797afd1a" FOREIGN KEY ("assessmentItemResponsesId") REFERENCES "assessmentItemResponse"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exercises" ADD CONSTRAINT "FK_e99f5f8d03827b1276286b48672" FOREIGN KEY ("onDashboardId") REFERENCES "settings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exercises" ADD CONSTRAINT "FK_ff49af7f485e2451b63c1870300" FOREIGN KEY ("onLeaderboardId") REFERENCES "settings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users_chats_chats" ADD CONSTRAINT "FK_017810da2080af92ae589a06db8" FOREIGN KEY ("usersId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "users_chats_chats" ADD CONSTRAINT "FK_6628b681b44362637c96ad2fab0" FOREIGN KEY ("chatsId") REFERENCES "chats"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workouts_exercises_exercises" ADD CONSTRAINT "FK_bfc966116a382a6f6b845ac15db" FOREIGN KEY ("workoutsId") REFERENCES "workouts"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "workouts_exercises_exercises" ADD CONSTRAINT "FK_13937e69e8ba290d5faafcec751" FOREIGN KEY ("exercisesId") REFERENCES "exercises"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "workouts_exercises_exercises" DROP CONSTRAINT "FK_13937e69e8ba290d5faafcec751"`);
        await queryRunner.query(`ALTER TABLE "workouts_exercises_exercises" DROP CONSTRAINT "FK_bfc966116a382a6f6b845ac15db"`);
        await queryRunner.query(`ALTER TABLE "users_chats_chats" DROP CONSTRAINT "FK_6628b681b44362637c96ad2fab0"`);
        await queryRunner.query(`ALTER TABLE "users_chats_chats" DROP CONSTRAINT "FK_017810da2080af92ae589a06db8"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_57de40bc620f456c7311aa3a1e6"`);
        await queryRunner.query(`ALTER TABLE "exercises" DROP CONSTRAINT "FK_ff49af7f485e2451b63c1870300"`);
        await queryRunner.query(`ALTER TABLE "exercises" DROP CONSTRAINT "FK_e99f5f8d03827b1276286b48672"`);
        await queryRunner.query(`ALTER TABLE "assessmentItems" DROP CONSTRAINT "FK_4f5214bc85f5fda317f797afd1a"`);
        await queryRunner.query(`ALTER TABLE "assessmentItems" DROP CONSTRAINT "FK_1fe04f9a82d0a5e58b9c3da8d0c"`);
        await queryRunner.query(`ALTER TABLE "assessmentItemResponse" DROP CONSTRAINT "FK_de0a3daae28e766c7b11e89f9e8"`);
        await queryRunner.query(`ALTER TABLE "assessmentItemResponse" DROP CONSTRAINT "FK_085b962c57b4c4f501207a3350f"`);
        await queryRunner.query(`ALTER TABLE "assessmentResponses" DROP CONSTRAINT "FK_78458898b3993eb848a6782c071"`);
        await queryRunner.query(`ALTER TABLE "assessmentResponses" DROP CONSTRAINT "FK_b14ffe8cedb517032ecc08d20a0"`);
        await queryRunner.query(`ALTER TABLE "athletes" DROP CONSTRAINT "FK_0fda0671cfa1c3156b6557a5add"`);
        await queryRunner.query(`ALTER TABLE "athletes" DROP CONSTRAINT "FK_6318488ea7158c8ab65882419d4"`);
        await queryRunner.query(`ALTER TABLE "athletes" DROP CONSTRAINT "FK_fede6c4b866bf0a869cfba5e0ab"`);
        await queryRunner.query(`ALTER TABLE "athleteSchedule" DROP CONSTRAINT "FK_dabf8cf192c6ba7583edacd3cd3"`);
        await queryRunner.query(`ALTER TABLE "coaches" DROP CONSTRAINT "FK_aff053106aac14fb7a780800bce"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_0b00d632e056e05b96b7c2594bc"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_2739419b1868e73398b68253f08"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_f127c2c8d3618ee635c96c68c4b"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_f548818d46a1315d4e1d5e62da5"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_36bc604c820bb9adc4c75cd4115"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_a23484d1055e34d75b25f616792"`);
        await queryRunner.query(`ALTER TABLE "files" DROP CONSTRAINT "FK_9415c86c94e166b3a99bd3986a4"`);
        await queryRunner.query(`ALTER TABLE "completedWorkouts" DROP CONSTRAINT "FK_a53f1794038304c744bacaa71fc"`);
        await queryRunner.query(`ALTER TABLE "pitches" DROP CONSTRAINT "FK_6f8fe7f1b32aca0b9dba1a9b4a4"`);
        await queryRunner.query(`ALTER TABLE "pitches" DROP CONSTRAINT "FK_bbcb61278db2649bb7bbe392d74"`);
        await queryRunner.query(`ALTER TABLE "completedExercises" DROP CONSTRAINT "FK_47eadb019d4da349af42995da72"`);
        await queryRunner.query(`ALTER TABLE "completedExercises" DROP CONSTRAINT "FK_d787040da51c16f05ca5aef40af"`);
        await queryRunner.query(`ALTER TABLE "questionnaireResponses" DROP CONSTRAINT "FK_9fff1a9413dfe068414944d779d"`);
        await queryRunner.query(`ALTER TABLE "questionnaireResponses" DROP CONSTRAINT "FK_d5a8869edfbeb74a0d8d1f28a9e"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_6f580671b044b44f55871b62330"`);
        await queryRunner.query(`ALTER TABLE "questions" DROP CONSTRAINT "FK_a25e444b4f0c7e666a72b702880"`);
        await queryRunner.query(`ALTER TABLE "questionResponse" DROP CONSTRAINT "FK_d4fe15ca6022f0f92008b6e203f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13937e69e8ba290d5faafcec75"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bfc966116a382a6f6b845ac15d"`);
        await queryRunner.query(`DROP TABLE "workouts_exercises_exercises"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6628b681b44362637c96ad2fab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_017810da2080af92ae589a06db"`);
        await queryRunner.query(`DROP TABLE "users_chats_chats"`);
        await queryRunner.query(`DROP TABLE "tickets"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TABLE "exercises"`);
        await queryRunner.query(`DROP TYPE "public"."exercises_type_enum"`);
        await queryRunner.query(`DROP TABLE "settings"`);
        await queryRunner.query(`DROP TABLE "workouts"`);
        await queryRunner.query(`DROP TABLE "assessments"`);
        await queryRunner.query(`DROP TABLE "assessmentItems"`);
        await queryRunner.query(`DROP TABLE "assessmentItemResponse"`);
        await queryRunner.query(`DROP TABLE "assessmentResponses"`);
        await queryRunner.query(`DROP TABLE "athletes"`);
        await queryRunner.query(`DROP TYPE "public"."athletes_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."athletes_handed_enum"`);
        await queryRunner.query(`DROP TABLE "athleteSchedule"`);
        await queryRunner.query(`DROP TABLE "coaches"`);
        await queryRunner.query(`DROP INDEX "public"."email_index"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TABLE "chats"`);
        await queryRunner.query(`DROP TABLE "files"`);
        await queryRunner.query(`DROP TABLE "completedWorkouts"`);
        await queryRunner.query(`DROP TYPE "public"."completedWorkouts_type_enum"`);
        await queryRunner.query(`DROP TABLE "pitches"`);
        await queryRunner.query(`DROP TYPE "public"."pitches_throwtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."pitches_type_enum"`);
        await queryRunner.query(`DROP TABLE "completedExercises"`);
        await queryRunner.query(`DROP TYPE "public"."completedExercises_type_enum"`);
        await queryRunner.query(`DROP TABLE "questionnaireResponses"`);
        await queryRunner.query(`DROP TABLE "questionnaires"`);
        await queryRunner.query(`DROP TABLE "questions"`);
        await queryRunner.query(`DROP TYPE "public"."questions_responsetype_enum"`);
        await queryRunner.query(`DROP TABLE "questionResponse"`);
    }

}
